app:
  test: 55
  db-access-type: jpa
  bot-client: rabbit
  scheduler:
    interval: 30000

server:
  port: 8081

spring:
  liquibase:
    enabled: false
  rabbitmq:
    port: 5672
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

logging:
  level:
    org:
      hibernate: INFO

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: "*"

    jmx:
      exposure:
        include: "*"

  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
