app:
  test: 55
  db-access-type: jpa
  bot-client: rabbit
  scheduler:
    interval: 30000

server:
  port: 8081

spring:
  liquibase:
    enabled: false
  rabbitmq:
    port: 5672
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true

logging:
  level:
    org:
      hibernate: INFO