version: "3.9"
services:
  postgresql:
    image: postgres:15
    hostname: postgres

    restart: always

    volumes:
      - postgres_vol:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

    ports:
      - 5432:5432

    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=secret
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    image:
      rabbitmq:management
    restart: no

volumes:
  postgres_vol:

networks:
  backend: