name: Bot module workflow

on:
  push:
    paths:
      - bot/**
    branches: [ "main" ]
  pull_request:
    paths:
      - bot/**
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper_bot

jobs:
  build:
    runs-on: ubuntu-latest
    needs: style-check

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build bot with Maven
        run: mvn package -DTG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }} -pl bot -am
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./bot
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Checkstyle
        run: mvn -DTG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }} -pl bot -am checkstyle:check
